### ISSUE TITLE
JoinLanding content not wrapping on mobile

### ISSUE THREAD

**Issue by ryancreatescopy** [ethereum/clrfund#89] opened 2021-05-26 10:10 UTC
![image](https://user-images.githubusercontent.com/40891631/119642727-ef651500-be12-11eb-8b13-7a397f238fb4.png)

This may only affect the `RoundClosed` state

**Comment by samajammin** [comment] 2021-06-08 15:34
Whoever picks this up: please confirm this is fixed for each round state.

Also worth investigating that all landing pages don't have this same issue...

**Comment by pettinarip** [comment] 2021-06-30 14:56
I've tested the following landing pages:
- Join: I couldn't reproduce the issue described here. I've tested in different resolutions, not only mobile, in different round states and the content is wrapping correctly. (however, I've found a small issue while testing => fixed in #181)
- Join/success: working correctly.
- Verify: working correctly.
- Verify/success: working correctly.
- Home: working correctly.

**Comment by corwintines** [comment] 2021-07-10 03:10
@samajammin @pettinarip @wackerow I think this is fine to close then?

**Comment by pettinarip** [comment] 2021-07-10 20:44
Yes, we can close it, in case someone sees the contrary we can reopen it.

**Closed as completed by pettinarip** 2021-07-10 20:44 UTC
Labels: bug, good first issue
