### ISSUE TITLE
Time left to reallocate no updating on round-info after finalization

### ISSUE THREAD

**Issue by wackerow** [ethereum/clrfund#98] opened 2021-06-01 22:15 UTC
![image](https://user-images.githubusercontent.com/54227730/120396165-ef6d8500-c2ea-11eb-8be5-2aec4bd4850c.png)
Round is over, round information showing "Time left to reallocate"

**Comment by samajammin** [comment] 2021-06-01 22:21
Closing this - duplicate of #95

**Closed as completed by samajammin** 2021-06-01 22:21 UTC
